name: Setup Node
description: 'Ensure NNode is installed, and setup pnpm with caching'

inputs:
  version:
    type: choice
    description: "Version to install"
    options:
      - '20.x'
      - '22.x'
    default: '20.x'
  js_folder:
    type: string
    description: 'Path to package.json'
    default: 'js'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        package_json_file: "${{ inputs.js_folder }}/package.json"

    - name: Set up Node ${{ inputs.version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.version }}
        cache: pnpm
        cache-dependency-path: "${{ inputs.js_folder }}/pnpm-lock.yaml"
